#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("YaSTroid.Resource", IsApplication=true)]

namespace YaSTroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int times_array = 2131099648;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int list_item_divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int status_green = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int status_red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int yast_system = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int yastroid_icon = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090023
			public const int add_group = 2131296291;
			
			// aapt resource value: 0x7f090025
			public const int add_server = 2131296293;
			
			// aapt resource value: 0x7f090020
			public const int bottomtext = 2131296288;
			
			// aapt resource value: 0x7f09000a
			public const int button_add_group = 2131296266;
			
			// aapt resource value: 0x7f09001c
			public const int button_add_server = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int button_save_server = 2131296285;
			
			// aapt resource value: 0x7f090007
			public const int edit_group_description = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int edit_group_icon = 2131296265;
			
			// aapt resource value: 0x7f090005
			public const int edit_group_name = 2131296261;
			
			// aapt resource value: 0x7f090015
			public const int edit_server_host = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int edit_server_name = 2131296275;
			
			// aapt resource value: 0x7f09001b
			public const int edit_server_pass = 2131296283;
			
			// aapt resource value: 0x7f090017
			public const int edit_server_port = 2131296279;
			
			// aapt resource value: 0x7f090019
			public const int edit_server_user = 2131296281;
			
			// aapt resource value: 0x7f090003
			public const int graph_view = 2131296259;
			
			// aapt resource value: 0x7f09000f
			public const int group_description = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int group_icon = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int group_name = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int module_icon = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int module_name = 2131296268;
			
			// aapt resource value: 0x7f090024
			public const int preferences = 2131296292;
			
			// aapt resource value: 0x7f090000
			public const int resource_type = 2131296256;
			
			// aapt resource value: 0x7f090011
			public const int server_address = 2131296273;
			
			// aapt resource value: 0x7f09001e
			public const int server_icon = 2131296286;
			
			// aapt resource value: 0x7f090010
			public const int server_name = 2131296272;
			
			// aapt resource value: 0x7f090002
			public const int spinner = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int spinner_label = 2131296257;
			
			// aapt resource value: 0x7f090021
			public const int system_status_icon = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int system_status_text = 2131296290;
			
			// aapt resource value: 0x7f09001f
			public const int toptext = 2131296287;
			
			// aapt resource value: 0x7f090006
			public const int txt_group_description = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int txt_group_icon = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int txt_group_name = 2131296260;
			
			// aapt resource value: 0x7f090014
			public const int txt_server_host = 2131296276;
			
			// aapt resource value: 0x7f090012
			public const int txt_server_name = 2131296274;
			
			// aapt resource value: 0x7f09001a
			public const int txt_server_pass = 2131296282;
			
			// aapt resource value: 0x7f090016
			public const int txt_server_port = 2131296278;
			
			// aapt resource value: 0x7f090018
			public const int txt_server_user = 2131296280;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int display_resource = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int groupadd = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int module_list_row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int server = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int server_group_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int server_group_list = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int server_header = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int serveradd = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int serveredit = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int serverlist = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int serverlistrow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int system_messages = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int system_messages_row = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int system_status = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int system_status_list_item = 2130903055;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int grouplistmenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int serverlistmenu = 2131230722;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05001b
			public const int add_group_button = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int add_group_description = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int add_group_icon = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int add_group_name = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int add_server_button = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int add_server_hostname = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int add_server_name = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int add_server_password = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int add_server_port = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int add_server_user = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int cpu_status_text = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int disk_status_text = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int display_resource_activity = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int group_add_activity = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int group_list_activity = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int heading = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int memory_status_text = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int network_status_text = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int no_groups_found = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int no_messages_found = 2131034143;
			
			// aapt resource value: 0x7f050002
			public const int no_servers_found = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int save_server_button = 2131034135;
			
			// aapt resource value: 0x7f050010
			public const int server_activity = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int server_add_activity = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int server_edit_activity = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int server_list_activity = 2131034120;
			
			// aapt resource value: 0x7f05001e
			public const int system_messages_activity = 2131034142;
			
			// aapt resource value: 0x7f050007
			public const int system_msgs_status_text = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int system_status_activity = 2131034123;
			
			// aapt resource value: 0x7f05001c
			public const int time_label = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int time_prompt = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int webyast_Server_info = 2131034144;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Theme_yastroid = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Widget_ListView = 2131165184;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
